### ISSUE TITLE
Use Weblate

### ISSUE THREAD

**Issue by eartharoid** [christmas-countdown/bot#57]
Use [Crowdin](https://crowdin.com/) (or maybe [Weblate](https://weblate.org/en-gb/)) for localisation.

**Comment by comradekingu** [comment]
Use Weblate. The tradition you are depicting is "Yule".

**Comment by eartharoid** [comment]
😕

**Comment by eartharoid** [comment]
Installed at https://i18n.capestar.net. I'll set it up as part of #56
