### ISSUE TITLE
Premium users, not premium guilds

### ISSUE THREAD

**Issue by eartharoid** [christmas-countdown/bot#64]
- Ko-fi assigns cool people role
- Bot checks if user has role (has role = is premium)
- If the owner of a server is premium, the server gets premium features.

**Or remove premium entirely?**

**Comment by RooRay** [comment]
Add descriptions to things, please and thank you

**Comment by eartharoid** [comment]
> Add descriptions to things, please and thank you

what are you talking about :wink:  :laughing:

**Comment by RooRay** [comment]
> > Add descriptions to things, please and thank you
> 
> what are you talking about 😉 😆

oh sorry I must’ve misread my GitHub it appears you did add a description after all 😔
